#27 #77 Improved functions for add, edit and search book
JayKandari/bookhive pull request #122
Opened 2020-10-07 10:50 UTC by shriaas2898

There were a lot of problems in making tables responsive specially if the contain a form, removed `listbook` edit page which contained huge table of book info.
* Wrote a function add  which adds a book in the DB and sets appropriate message in `$_SESSION["success"]`/`$_SESSION["error"]`. This function does not contain HTML code and is called when the form is submitted.
* Wrote a function edit which updates book information in DB  and sets appropriate message in `$_SESSION["success"]`/`$_SESSION["error"]`
     - Also added code to update image using file picker instead of specifying the path.
     - When the cover image is updated in the database the corresponding old file is deleted from files.

* Wrote a function `delete` which deletes the book record from the table and its cover image from files.
* Wrote a function `search` which searches book by `title`, `author` or `category`.
* Wrote a function `searchById` which searches book by its `id`.
* Added an option to edit When admin searches any book.
* Reused `AddBook` page to edit book when id is passed as a `GET` parameter.

This a huge commit would recommend everyone to review it. @JayKandari @rahulsavaria @guptahemant @AJV009 @anjali-rathod @pragzii3896

2020-10-07 11:06 UTC, AJV009 commented
Nice 👍👍👍
I'll soon make a pull from your branch and test em! 😅

2020-10-07 12:40 UTC, rahulsavaria requested changes

2020-10-07 12:40 UTC, rahulsavaria commented on public-html/addbook.php
> +	<div class="container">
incorrect indentation

2020-10-07 12:50 UTC, shriaas2898 commented
@rahulsavaria made the requested changes

2020-10-07 20:44 UTC, AJV009 commented
@shriaas2898 check this out -> https://vod-progressive.akamaized.net/exp=1602107008~acl=%2A%2F2067490946.mp4%2A~hmac=2df89f68267d83280e22ad547e893b767986fc637bc25e7e70bdbd20ab2e9d97/vimeo-prod-skyfire-std-us/01/3184/18/465921565/2067490946.mp4

2020-10-08 03:57 UTC, guptahemant requested changes

2020-10-08 03:57 UTC, guptahemant commented on public-html/addbook.php
> +            $_SESSION["error"] = "No books found";
Please add a follow up to replace to use of session variable directly with a get and set method in session class. Also if possible add appropriate methods to store and show session messages from session variables.

2020-10-08 03:57 UTC, guptahemant commented on public-html/searchbook.php
> +// use src\Connection;
remove this if not needed.

2020-10-08 03:57 UTC, guptahemant commented on public-html/searchbook.php
> +                            if (isset($_SESSION["logged_in"])) {
use the session class to detect if a user is logged in.

2020-10-08 03:57 UTC, guptahemant commented on resources/src/books.php
> +      var_dump($book_details);
Remove debug statement.

2020-10-08 03:59 UTC, shriaas2898 commented
> @shriaas2898
> The edituser table seems to be messed up
> check this out -> https://vod-progressive.akamaized.net/exp=1602107008~acl=%2A%2F2067490946.mp4%2A~hmac=2df89f68267d83280e22ad547e893b767986fc637bc25e7e70bdbd20ab2e9d97/vimeo-prod-skyfire-std-us/01/3184/18/465921565/2067490946.mp4

This says access denied. Also edit user table's UI is messed up and I haven't worked on it we have to remove tables anyways.

2020-10-08 04:14 UTC, AJV009 commented
> > @shriaas2898
> > The edituser table seems to be messed up
> > check this out -> https://vod-progressive.akamaized.net/exp=1602107008~acl=%2A%2F2067490946.mp4%2A~hmac=2df89f68267d83280e22ad547e893b767986fc637bc25e7e70bdbd20ab2e9d97/vimeo-prod-skyfire-std-us/01/3184/18/465921565/2067490946.mp4
> 
> This says access denied. Also edit user table's UI is messed up and I haven't worked on it we have to remove tables anyways.

:see_no_evil:  :laughing: 
I thought other tables would get effected too

2020-10-08 05:26 UTC, shriaas2898 commented on public-html/addbook.php
> +            $_SESSION["error"] = "No books found";
Sure I'll create an issue for this.

2020-10-08 07:00 UTC, guptahemant approved these changes

2020-10-08 07:03 UTC, rahulsavaria approved these changes

2020-10-08 07:22 UTC, merged